### ISSUE TITLE
weird org load-path issue

### ISSUE THREAD

**Issue by hrehfeld** [radian-software/radian#495]
Hard to give a good report, but I just had a situation where:

- system org was in load-path
- straight org wasn't (!)

org-agenda then fails due to functions being used from straight/git org files (how?!) trying to call functions from system org, after a `(require 'org)` I had in deep in my own config for private org settings.

Can you check if an actual `(require 'org)` causes problems for you as well? Is that code-path maybe never checked because radian uses straight directly to require?

Or maybe org-contrib is somehow using straight files (but this was from something in org/, not in org-contrib/), but org isn't?

I'm using relatively new git pull (a week or so old), radian is supposed to load org-contrib (not in disabled packages, and var is t), was using straight-pull-all last week.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/radian-software/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
